# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: reccenterhq-jrails 0.8.6 ruby lib

Gem::Specification.new do |s|
  s.name = "reccenterhq-jrails"
  s.version = "0.8.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aaron Eisenberger", "Patrick Hurley", "Brent Miller"]
  s.date = "2017-09-28"
  s.description = "Using jRails, you can get all of the same default Rails helpers for javascript functionality using the lighter jQuery library."
  s.email = "jerrod@reccenter.com"
  s.executables = ["jrails"]
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "bin/jrails",
    "init.rb",
    "install.rb",
    "lib/jrails.rb",
    "lib/jrails/asset_tag_ext.rb",
    "lib/jrails/jquery_selector_assertions.rb",
    "lib/jrails/jrails.rb",
    "lib/tasks/jrails.rake",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/reccenterhq/jrails"
  s.rubygems_version = "2.4.6"
  s.summary = "jRails is a drop-in jQuery replacement for the Rails Prototype/script.aculo.us helpers."
end

